// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxiunkpqkaivjkquztke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4aXVua3Bxa2FpdmprcXV6dGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTQyNjEsImV4cCI6MjA2NjIzMDI2MX0.D1okVZbOeGaDSSLaM5ROYL1wIXRSR7oqHWA63mVlO_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});